### ISSUE TITLE
Not work. On  my ST7565 5pin: DC(RS or A0)  RS CLK  CS  DATA

### ISSUE THREAD

**Issue by selevo** [bitbank2/bb_uc1701#1]
CS not used (always on GND)
DC(RS or A0)  RS CLK  DATA - used

What start my LCD on your  lib ?
I  tested LCD on this code: https://github.com/robsoncouto/ST7565-T3
And  all good work but  this  lib used RAM and not start on  litle chips.
-
Thank's

**Comment by bitbank2** [comment]
I merged several libraries together to form a new one -->

https://github.com/bitbank2/OneBitDisplay

That library supports your display, has a lot of new features and allows you to not uses any RAM for a backbuffer if you like.
