### ISSUE TITLE
About buffer transfers

### ISSUE THREAD

**Issue by nopnop2002** [bitbank2/bb_uc1701#2]
Thank you for providing a useful library.

I found a small problem.

uc1701WriteDataBlock() uses buffer transfers.

```
  while (iLen) // internal buffer is only 32 bytes
  {
     if (iLen >= 32)
        i = 32;
     else
        i = iLen;
     SPI.transfer(ucBuf, i);  -----> the received data is stored in the buffer in-place
     ucBuf += i;
     iLen -= i;
  }
```

In case of buffer transfers the received data is stored in the buffer in-place (the old data is replaced with the data received).

So destroy ucBuf.

Thank you.

**Comment by bitbank2** [comment]
I understand the situation. I've moved this code into a new library (OneBitDisplay) that has more functionality. I don't plan on doing additional development on this code. Please retest on that library and I'll see if I can make any changes if needed.
